# Basic config
baseURL = "https://jzjf202703.github.io/"
theme = "hugo-simple"
languageCode = "zh-Hans"                # zh-Hans
title = "交中嘉分2027届3班"
copyright = "© 2024"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "交中嘉分2027届3班"
description = "交中嘉分2027届3班博客"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = false

[params.author]
name = "交中嘉分2027届3班"
email = "espyjump@163.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Blog"
pageRef = "https://jzjf202703.github.io/blogs"
weight = 20

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
